use_frameworks!

target 'CBCameraViewController_Example' do
  pod 'CBCameraViewController', :path => '/Users/cathy810218/Developer/cblue/CBCameraViewController'

  target 'CBCameraViewController_Tests' do
    inherit! :search_paths

    
  end
end
