use_frameworks!

target 'CBCameraViewController_Example' do

  pod 'CBCameraViewController', :path => '../'
  pod 'SnapKit'


  target 'CBCameraViewController_Tests' do
    inherit! :search_paths

    
  end
end
